### ISSUE TITLE
Ready for QC

### ISSUE THREAD

**Issue by kylebunting** [microsoft/MCW-Migrating-SQL-databases-to-Azure#1]
The Migrating SQL databases to Azure MCW is ready for QC and publishing.

**Comment by DawnmarieDesJardins** [comment]
@kylebunting 
Hello!  Please flatten images and review reading order in the PPT for slides 15, 28, 29, 30 & 31.
Thanks, Dawnamrie

**Comment by kylebunting** [comment]
@DawnmarieDesJardins, the slides have been updated. This can now be closed out.

**Comment by DawnmarieDesJardins** [comment]
@kylebunting - you're awesome, thank you!  Closing issue - resolved.
