### ISSUE TITLE
Before HOL setup fails

### ISSUE THREAD

**Issue by infosatheesh2020** [microsoft/MCW-Migrating-SQL-databases-to-Azure#11]
The ARM template for before HOL fails with below error, replicated multiple times in different subscription

{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "Conflict",
      "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VnetSubnetConflictWithIntendedPolicy\",\r\n        \"message\": \"Route Table. (https://go.microsoft.com/fwlink/?linkid=871071)\"\r\n      }\r\n    ]\r\n  }\r\n}"
    }
  ]
}

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #12
