### ISSUE TITLE
Microsoft.Sql/managedInstances Conflict while deploying Microsoft.Template

### ISSUE THREAD

**Issue by J4DR3** [microsoft/MCW-Migrating-SQL-databases-to-Azure#15]
While deploying the ARM template, this error makes it unable to finish deployment:
{
    "status": "Failed",
    "error": {
        "code": "ResourceDeploymentFailure",
        "message": "The resource operation completed with terminal provisioning state 'Failed'.",
        "details": [
            {
                "code": "VnetSubnetConflictWithIntendedPolicy",
                "message": "Precondition failed.. (https://go.microsoft.com/fwlink/?linkid=871071)"
            }
        ]
    }
}

The PowerShell command from this link is not working. 
I've tried to deploy this template 6 times, same error appears every time.

**Comment by kylebunting** [comment]
@J4DR3, please take a look at issue #14. This is most likely a region or backend resource provisioning issue, unrelated to the ARM template.

**Comment by kylebunting** [comment]
@J4DR3 were you able to review the previous issues to see if that helped to resolve your error?

**Comment by J4DR3** [comment]
Yes, thank you for quick feedback. Selecting East US 2 as a region for this resource group enabled me to deploy this template, I'm working on finishing the migration. I think that You should specify that selecting this region is a key to successful deployment in Before the HOL file, this issue stopped a few people in my group from finishing this lab.
Best Regards



Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by kylebunting** [comment]
Thanks for the feedback. Unfortunately, the regions which enable people to be successful isn't always the same. I, for example, always have to use West US 2. I think it may depend on the user's subscription and where resources are available.

I've added a note in the Before the HOL guide providing some work-around instructions should anyone encounter an error running the ARM template.
