### ISSUE TITLE
[TYPO] SERVER NAME :200.

### ISSUE THREAD

**Issue by Tailcloud** [microsoft/MCW-Migrating-SQL-databases-to-Azure#16]
There is a typing error of step6 of the step to step document,
Server name: Select SQLSERVER200. >> should be **SQLSERVER2008**. 
Otherwise, it will show
>  Error:40 
'Connection to the server failed.
> Validator 'Microsoft.SqlServer.Migration.Core.Validators.SupportedDatabaseEnvironmentValidator' failed to validate data.'

**Comment by DawnmarieDesJardins** [comment]
@Tailcloud @kylebunting @timahenning 

Thanks for the heads up!  This has been corrected, closing as complete.
