### ISSUE TITLE
Not possible to connect to the SQL Server with WorkshopUser credentials

### ISSUE THREAD

**Issue by aqyx** [microsoft/MCW-Migrating-SQL-databases-to-Azure#17]
Task 3, Step 5 asks you to connect to the SQL Server as WorkshopUser, but the the connection fails.

![image](https://user-images.githubusercontent.com/13008664/81828863-2cc17200-9532-11ea-900a-99d54f4d735b.png)

**Comment by kylebunting** [comment]
@aqyx, creation of the Workshop user account in SQL Server is handled automatically by the [SqlServer2008 VM config script](https://github.com/microsoft/MCW-Migrating-SQL-databases-to-Azure/blob/master/Hands-on%20lab/lab-files/ARM-template/configure-sqlvm.ps1). Based on the issues you are reporting, I'm guessing the script failed to run correctly or was not completed for some reason. I will test the ARM template to make sure the script is still running as expected during VM creation.

**Comment by aqyx** [comment]
@kylebunting I didn't have same issue with my second deployment, so it may have been a one-off issue.
