### ISSUE TITLE
Ex 7, Task 2: READ_WRITE label is not replaced with READONLY after setting ApplicationIntent

### ISSUE THREAD

**Issue by aqyx** [microsoft/MCW-Migrating-SQL-databases-to-Azure#19]
After adding the ApplicationIntent=ReadOnly value to the TailspinToysReadOnlyContect, read READONLY label is not visible on the website after refreshing, even after restarting the app service.

The connection string has been copied and pasted from the lab guide, replacing the server address, but the page on the website doesn't appear to update as expected.

![image](https://user-images.githubusercontent.com/13008664/81930115-022df280-95e0-11ea-939c-835f7388faa8.png)

![image](https://user-images.githubusercontent.com/13008664/81930160-0eb24b00-95e0-11ea-8b8e-1a2ff30e9726.png)

**Comment by kylebunting** [comment]
@aqyx, I have just run through this and am getting the `READ_ONLY` message, as expected. Could you try to open the website in an InCognito browser window or use the developer tools to do an empty cache and hard refresh? I know sometimes this can be caused by browser caching.

**Comment by aqyx** [comment]
@kylebunting Must have been a transient or caching issue, didn't reoccur when I redeployed and ran through the labs again. Thanks for checking.
