### ISSUE TITLE
ARM Template Failing on SQL MI Deployment

### ISSUE THREAD

**Issue by chrisbaudo** [microsoft/MCW-Migrating-SQL-databases-to-Azure#2]
I've attempted to deploy the ARM template, but receive the following error message after about 30 minutes:

"The service objective assignment for the database has failed. Please contact Microsoft customer support and provide the server name, database name and activity ID."

However, after the ARM template deployment completely fails, I can manually deploy the SQL MI instance without issues.  Has anyone else had this issue?  My subscription core quota is high enough and I'm accepting all the ARM template defaults before deployment.

Please reach out if you need more information.

**Comment by DawnmarieDesJardins** [comment]
@kylebunting 
Please review/advise.

**Comment by ac2707** [comment]
Same with me - ARM template deployment failing.
Error below 
 - {"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"VnetSubnetConflictWithIntendedPolicy\",\r\n \"message\": \"Route Table. (https://go.microsoft.com/fwlink/?linkid=871071)

Please advise.
I have also earlier deployed SQL MI manually.

**Comment by ac2707** [comment]
Hi @kylebunting  - any update on this ? Please advise..

Thanks
Aarti

**Comment by kylebunting** [comment]
@ac2707, I'll look at this today.

**Comment by ernani** [comment]
I am receiving the same type of error, which is really weird.

**Comment by kylebunting** [comment]
@ernani, are you not using the ARM template provided with the lab? It could help me troubleshoot if I know that you are getting an error just trying to provision SQL MI and that perhaps it is not related to the ARM template.

**Comment by kylebunting** [comment]
I've pushed an update to the ARM template to fix this issue. Please let me know if you continue to have problems.

**Comment by chrisbaudo** [comment]
I just tested the ARM template and it works without issues.  Thanks.

**Comment by ernani** [comment]
> @ernani, are you not using the ARM template provided with the lab? It could help me troubleshoot if I know that you are getting an error just trying to provision SQL MI and that perhaps it is not related to the ARM template.

In my case it is related to this issue: https://github.com/Azure/azure-cli/issues/10295
