### ISSUE TITLE
June 2020 Update Suggestions

### ISSUE THREAD

**Issue by timahenning** [microsoft/MCW-Migrating-SQL-databases-to-Azure#20]
WDS Updates:
Update SSRS content and add newer Power BI integration
Update references to the new Azure SQL branding.
Add SQL MI related security benefits to the customer conversation.

Lab Updates:
Test all tasks in the labs
Update screenshots
Update references to new Azure SQL branding
Investigate adding SQL accounts to initial automation script
Task 5: Create a service principal
Check to see if this task needs to be updated or can be automated further. Possibly use a managed identity.

**Comment by timahenning** [comment]
Sanjay requested on 6/12/2020 we change the workshop references from Tailspin Toys to World Wide Importers.  Just labels.  Keep database etc.

**Comment by DawnmarieDesJardins** [comment]
Closing issue.  Update was changed to June 2020 test/fix
