### ISSUE TITLE
Not able to login using WorkShopUser credetials.

### ISSUE THREAD

**Issue by sumitmalik51** [microsoft/MCW-Migrating-SQL-databases-to-Azure#23]
I am not able to login using WorkShopUser account. i found that this is because SQL Server authentication mode windows only. and this is not changing from the Configure-sqlVM.ps1, I am able to login after enabled the Mixed Authentication mode for SQL Server. 

i have added this query in powershell script.

$query = "USE [master]
GO
EXEC xp_instance_regwrite N'HKEY_LOCAL_MACHINE', 
     N'Software\Microsoft\MSSQLServer\MSSQLServer',
     N'LoginMode', REG_DWORD, 2
GO"
Invoke-Sqlcmd $query -QueryTimeout 3600 -ServerInstance $ServerName

Restart-Service -Force MSSQLSERVER

**Comment by kylebunting** [comment]
@sumitmalik51, the steps in the lab have you use the SQL Server Settings tab when provisioning the VM to handle setting the SQL Server authentication mode to mixed. This is handled by the ARM template when using the automated resource deployment.

Did you use the ARM template to set up the lab resources, or did you set up the VM manually?

**Comment by sumitmalik51** [comment]
Thanks for the information @kylebunting , no i am not using the ARM template. closing the issue.

Thanks
