### ISSUE TITLE
September 2020 Updates

### ISSUE THREAD

**Issue by timahenning** [microsoft/MCW-Migrating-SQL-databases-to-Azure#24]
WDS Updates:
Update SSRS content and add newer Power BI integration
Update references to the new Azure SQL branding.
Add SQL MI related security benefits to the customer conversation.

Lab Updates:
Test all tasks in the labs
Update screenshots
Update references to new Azure SQL branding
Investigate adding SQL accounts to initial automation script
Task 5: Create a service principal
Check to see if this task needs to be updated or can be automated further. Possibly use a managed identity.

**Comment by kylebunting** [comment]
Pull request #26 submitted to cover the requested updates.

I included updates to rebrand the resources used in the hands-on lab to Wide World Importers (WWI) from Tailspin Toys. This should set up the next update to accommodate the change over to a manufacturing-based scenario from the current gaming one.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as complete with merge of PR #26
