### ISSUE TITLE
web app is not loading

### ISSUE THREAD

**Issue by sumitmalik51** [microsoft/MCW-Migrating-SQL-databases-to-Azure#29]
In exercise 4 task2:- 
I have followed all the steps but the web app is not getting loaded.

* subnet is connected with web app
* Connectionstring is also updated with the database strings.

Getting the following error page.
![image](https://user-images.githubusercontent.com/45102602/101464606-dbad1b80-3964-11eb-8b19-a10bff2d8773.png)

**Comment by kylebunting** [comment]
@sumitmalik51, did you try restarting the web app? Sometimes that is required and other times it just takes a few minutes for the VNet integration to take effect.

**Comment by sumitmalik51** [comment]
Yes I tried restarting the web app multiple times but its not working. Also its almost more then 2 hrs since I connected the subnet.

**Comment by kylebunting** [comment]
Can you try removing the VNet integration and then adding it back in?

**Comment by sumitmalik51** [comment]
I already tried that also, this start happening with the WWI database only

**Comment by sumitmalik51** [comment]
Hi, 
Is there have any update on this issues?

**Comment by sumitmalik51** [comment]
@DawnmarieDesJardins  I can understand this but we are having deliveries for this workshop everyday in AIW event and we are getting multiple escalations for this issue .

**Comment by DawnmarieDesJardins** [comment]
@sumitmalik51 
Thanks Sumit, I will forward to our authors.  Moving forward, if you have upcoming presentations, we need to know when you open the original issue to help up prioritize.  Please provide us with that information and the date of the presentation so we can best help you.

**Comment by timahenning** [comment]
I am deploying the resources right now in preparation for debugging this issue.  As you are aware, it takes hours to create the resources.

**Comment by kylebunting** [comment]
@sumitmalik51, I just tested through this and was able to connect the web application to the SQL MI using VNet integration without issue. I had to restart the web app to get it to load the web page, but it all worked.

I also continued with the steps to update the Read-Only connection string, and that part worked as expected too.

Could you tell me more about the environment you are using? Was it deployed using the ARM template provided with this hands-on lab? If this is a Spektra environment, would it be possible for you to send me the environment details so I can test there? My email is kyle@solliance.net.

**Comment by sumitmalik51** [comment]
@kylebunting ,
Sure I will send you environment tomorrow.

Thanks

**Comment by DawnmarieDesJardins** [comment]
@sumitmalik51 @kylebunting 
Hello!  Just checking in.  Did this get sent?

**Comment by kylebunting** [comment]
I have not received an environment to test in.

**Comment by sumitmalik51** [comment]
Hello @kylebunting , I have shared the environment URL with you.

**Comment by kylebunting** [comment]
@sumitmalik51, I was able to get this working without issue in the environment you provided. Everything is still in place, so you can check things there.

I think it might just be a matter of making sure the web app restarts successfully.

I also noticed that you are using the General Purpose pricing tier for SQL MI. For this workshop, it needs to be the Business Critical tier, or Exercise 7 will not work. That relies on one of the read-only replicas you get with business critical to provide a read-only copy of the database to connect to. When using the general purpose tier, you don’t get a read-only replica, so it will always connect to the main database in a READ_WRITE mode.

Kyle

**Comment by kylebunting** [comment]
@sumitmalik51, can you also confirm for me that the web app you are trying to deploy with that environment is the `TailspinToysWeb` web app project and not the newer `WideWorldImporters` app?

If you are trying to use the newer `WideWorldImporters` app, the connection string names would need to be updated accordingly in the Web App's configuration.

**Comment by sumitmalik51** [comment]
Hi @kylebunting , I have tried the newer WideWorldImporters app Also, It's okay I will try to run again and will reopen this issue if needed.
Thanks for your support kyle.
