### ISSUE TITLE
Before the labs Appendix A link broken

### ISSUE THREAD

**Issue by amthomas46** [microsoft/MCW-Migrating-SQL-databases-to-Azure#3]
https://github.com/microsoft/MCW-Migrating-SQL-databases-to-Azure/blob/master/Hands-on%20lab/Appendix-A

Needs a '.md' to the end of the url.

Thanks,
Anna

**Comment by DawnmarieDesJardins** [comment]
@kylebunting 
Hi Kyle...does this also close issue #2?

**Comment by kylebunting** [comment]
No. I am still troubleshooting that one. Hope to have it done tomorrow.

Kyle

On Aug 12, 2019, at 4:44 PM, Dawnmarie DesJardins <notifications@github.com> wrote:

@kylebunting <https://github.com/kylebunting>
Hi Kyle...does this also close issue #2 <https://github.com/microsoft/MCW-Migrating-SQL-databases-to-Azure/issues/2>?
