### ISSUE TITLE
Why Trial subscriptions will not work ?

### ISSUE THREAD

**Issue by mamhh** [microsoft/MCW-Migrating-SQL-databases-to-Azure#32]
Could you please elaborate more on this ? Why Trial subscriptions will not work ?

**Comment by kylebunting** [comment]
@mamhh, SQL MI is not available when using a free Azure trial account.

https://azure.microsoft.com/en-us/free/free-account-faq/

**Comment by mamhh** [comment]
> @mamhh, SQL MI is not available when using a free Azure trial account.
> 
> https://azure.microsoft.com/en-us/free/free-account-faq/

It's mentioned in the referenced url .. please elaborate further..

**Comment by kylebunting** [comment]
@mamhh, that's the point. The services listed on the link are the services that you can create when using a free trial account. SQL MI is not one of the services you can create using that kind of account.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as complete.
