### ISSUE TITLE
Customer "objections" needs to be replaced with "objectives"

### ISSUE THREAD

**Issue by lswords** [microsoft/MCW-Migrating-SQL-databases-to-Azure#33]
In the deck WDS trainer presentation - Migrating SQL databases to Azure.pptx, there are multiple references to "Customer objections".  The correct term should be "Customer objectives"

**Comment by kylebunting** [comment]
@lswords, the correct term is "Customer objections." Customer objections describe the questions and concerns a customer has about migrating their databases and systems to azure.

**Comment by lswords** [comment]
I would call them questions and concerns then.  Objections are "an expression or feeling of disapproval or opposition; a reason for disagreeing".  The fact they WANT to move to the cloud is not an objection.  https://github.com/microsoft/MCW-Migrating-SQL-databases-to-Azure/blob/master/Whiteboard%20design%20session/WDS%20student%20guide%20-%20Migrating%20SQL%20databases%20to%20Azure.md#customer-objections are not objections, they are questions/concerns like you describe.

**Comment by kylebunting** [comment]
@lswords, I'll pass this along to the team that manages these at Microsoft. This is the same language that is used throughout all of the cloud workshops, so not something I am able to change.
