### ISSUE TITLE
Required permissions clarification

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [microsoft/MCW-Migrating-SQL-databases-to-Azure#34]
I received this information via Teams chat.  Creating a GitHub issue so it can be reviewed and addressed.  Thank you!

Seems like  some information in this doc is not correct - there is no need to have owner role in the resource group:

To migrate, the required permission is contributor role in sub, as specified in this official doc: https://docs.microsoft.com/en-au/azure/dms/tutorial-sql-server-managed-instance-online

Azure Database Migration Service requires the Contributor permission on the subscription for the specified Application ID. Alternatively, you can create custom roles that grant the specific permissions that Azure Database Migration Service requires. For step-by-step guidance about using custom roles, see the article Custom roles for SQL Server to SQL Managed Instance online migrations.

**Comment by DawnmarieDesJardins** [comment]
@kylebunting
Hey Kyle!  Can you give an ETA for this?  I don't think PR #37 addressed this one.

**Comment by kylebunting** [comment]
@DawnmarieDesJardins, I'll have it done today (Tuesday, March 30).

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #38
