### ISSUE TITLE
Excercise4>Task1> 3

### ISSUE THREAD

**Issue by Katelyn98098s** [microsoft/MCW-Migrating-SQL-databases-to-Azure#35]
Unable to save point-to-site configuration.

Here is what I input.
- Address pool: 192.168.0.0/16
- Tunnel type: Select SSTP (SSL).
- Authentication type: Choose Azure certificate

When I followed the instruction 'Excercise4>Task1> 3 ' Save button is disabled.

Do I need to add Root certificates?

**Comment by shkumesh** [comment]
I also have the same issue. We going to deliver a workshop using these lab resources. So could you please fix this?

**Comment by kylebunting** [comment]
When are you delivering the workshop?

**Comment by shkumesh** [comment]
30th of March.
