### ISSUE TITLE
Lab need update to ease up student worshops

### ISSUE THREAD

**Issue by JulienAlbo** [microsoft/MCW-Migrating-SQL-databases-to-Azure#39]
Created on the behalf of Tim Henning. I will soon resolve this issue. Hereinafter content is from Tim's email.

We need someone to be able to follow the instructions and run through the lab.  Old Azure images will need to be updated. Small technical fixes may need to be applied. (less than about 1 hour, otherwise we need to go back to MS).  Instructions may need to be updated.  The whiteboard design session may need to be updated as well. Highly unlikely.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #40
