### ISSUE TITLE
October 2021 suggestions

### ISSUE THREAD

**Issue by timahenning** [microsoft/MCW-Migrating-SQL-databases-to-Azure#41]

**Comment by kylebunting** [comment]
I recommend the following updates to the MCW:

WDS:

- My experience with this lab so far is that a lot of folks want to recommend migrating to Cosmos DB when doing the WDS, as the company is a game developer. It would be good to mention something about the customer having looked at NoSQL database options in the `Customer situation` section and that they feel the complexity of that migration would be too time-consuming for them at this time, but that they are open to that once they have completed their current cloud migration.
- Mention support for [cross-instance message exchange on Azure SQL Managed Instance](https://azure.microsoft.com/en-us/updates/service-broker-message-exchange-for-azure-sql-managed-instance-in-public-preview/). (Currently in public preview)
- Work the need for [Azure Active Directory integration with SQL MI](https://docs.microsoft.com/en-us/azure/azure-sql/managed-instance/sql-managed-instance-paas-overview#azure-active-directory-integration) into the customer scenario.  This should also be mentioned in the preferred solution under the "What are some of the features available in Azure SQL Managed Instance that can help improve WWI's security posture?" question.
- 

HOL:

- Update screenshots as needed.
- Test and fix all components based on any Azure updates to services involved.
- Consider adding an exercise for setting up and using Azure Migrate to assess the readiness of the SQL Server database to migrate to Azure SQL Database. This would rely on the DMA assessment performed already in the lab. Steps should follow this article pretty closely: https://docs.microsoft.com/en-us/sql/dma/dma-assess-sql-data-estate-to-sqldb?view=sql-server-ver15

**Comment by DawnmarieDesJardins** [comment]
Additional feedback:
  (received via email)
I think we need a section of what value add customer can drive when migrating to Azure. 
 
Perhaps even being able to run an ML model on the gaming data to help detect for cheats or something along the way. I do understand about the timing challenge so perhaps another item to put into the WDS session part of it.

**Comment by DawnmarieDesJardins** [comment]
Closing issue with merge of PR #42
