### ISSUE TITLE
Getting issue in Configure SQL Data Discovery and Classification

### ISSUE THREAD

**Issue by akn9050** [microsoft/MCW-Migrating-SQL-databases-to-Azure#9]
There is an issue which we are getting when saving the classifications data in **Data Discovery & Classification** in [Exercise 5, Task2, Step 11](https://github.com/microsoft/MCW-Migrating-SQL-databases-to-Azure/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Migrating%20SQL%20databases%20to%20Azure.md#task-2-configure-sql-data-discovery-and-classification)
Below is the screen shot error when we are adding the recommended classifications and saving the classifications.  

![image](https://user-images.githubusercontent.com/27498287/69266241-cf86dc80-0bf0-11ea-8f1c-1dba4e612e68.png)

**Comment by DawnmarieDesJardins** [comment]
@akn9050 
Thanks Amit.  I'll have one of our authors take a look at this and get back to you.

**Comment by kylebunting** [comment]
@akn9050, thanks for submitting the issue. This is a known issue, and there is a note listed under Exercise 5, Task 2 Step 11 of the hands-on lab guide addressing it. 

> **Note**: This feature is still in preview. If you receive an error when saving, try returning to the Advanced Data Security blade, and selecting the Data Discovery & Classification tile again to see the results.

Unfortunately, it is an issue with the service and not something I can correct at this point.

**Comment by akn9050** [comment]
Hi @kylebunting does it make sense if I raise a support case with MSFT for this.

**Comment by kylebunting** [comment]
@akn9050, you could. As far as I know, Data Discovery and Classification is still in preview for SQL MI, so they may already be aware of the issue, but it not it couldn't hurt.

**Comment by akn9050** [comment]
thanks
